build:
  binary: ff
  main: ./
  goos:
    - windows
    - darwin
    - linux
    - freebsd
  goarch:
    - '386'
    - amd64
    - arm
    - arm64
  goarm:
    - '6'
  ignore:
    - goos: darwin
      goarch: '386'
  env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w # Don't set main.version.

gomod:
  proxy: true

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE
      - completion/**/*
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "ff_checksums.txt"

nfpms:
  - vendor: feedflux
    homepage: https://github.com/NOBLES5E/FeedFlux
    maintainer: Shawn Lian <shawn@shawnlian.com>
    description: FeedFlux is a lightweight tool developed in Go that parses various feeds such as RSS and Atom into a unified JSON format, with the ability to record and resume fetching progress.
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
